

#ifndef HARDWARE_H_
#define HARDWARE_H_

#define LED_LATCH_ADDRESS	0x1002
#define LED_RUN_BITMASK		0x01
#define LED_1_BITMASK		0x02
#define LED_2_BITMASK		0x04
#define LED_RX_BITMASK		0x08
#define LED_TX_BITMASK		0x10
#define LED_ERR_BITMASK		0x20
#define WATCHDOG_PIO_BIT	0x8000

#endif /* HARDWARE_H_ */
