


#define IX_NPE_IMAGE_INCLUDE 1

#define IX_NPE_IMAGE_OMIT    0


#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEA_HSS0 0x00010000
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEA_HSS0_ATM_SPHY_1_PORT 0x00020000
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEA_HSS0_ATM_MPHY_1_PORT 0x00030000
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEA_ATM_MPHY_12_PORT 0x00040000
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEA_DMA 0x00150100
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEA_HSS_2_PORT 0x00090000
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEA_ETH 0x10800200
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEA_ETH_LEARN_FILTER_SPAN_FIREWALL 0x10800200
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEA_ETH_LEARN_FILTER_SPAN_FIREWALL_VLAN_QOS 0x10810200
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEA_ETH_SPAN_FIREWALL_VLAN_QOS_HDR_CONV 0x10820200
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEB_ETH 0x01000200
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEB_ETH_LEARN_FILTER_SPAN_FIREWALL 0x01000200
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEB_ETH_LEARN_FILTER_SPAN_FIREWALL_VLAN_QOS 0x01010200
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEB_ETH_SPAN_FIREWALL_VLAN_QOS_HDR_CONV 0x01020200
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEB_DMA 0x01020100
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEC_ETH 0x02000200
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEC_ETH_LEARN_FILTER_SPAN_FIREWALL 0x02000200
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEC_ETH_LEARN_FILTER_SPAN_FIREWALL_VLAN_QOS 0x02010200
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEC_ETH_SPAN_FIREWALL_VLAN_QOS_HDR_CONV 0x02020200
#endif

#if IX_NPE_IMAGE_INCLUDE
#define IX_NPEDL_NPEIMAGE_NPEC_DMA 0x02080100
#endif

/* Number of NPE firmware images in this library */
#define IX_NPE_MICROCODE_AVAILABLE_VERSIONS_COUNT 17

/* Location of Microcode Images */
#ifdef IX_NPE_MICROCODE_FIRMWARE_INCLUDED
#ifdef IX_NPEDL_READ_MICROCODE_FROM_FILE

extern UINT32* ixNpeMicrocode_binaryArray;

#else

extern unsigned IxNpeMicrocode_array[];

#endif
#endif

#undef IX_NPEDL_NPEIMAGE_NPEA_HSS0
#undef IX_NPEDL_NPEIMAGE_NPEA_HSS0_ATM_SPHY_1_PORT
#undef IX_NPEDL_NPEIMAGE_NPEA_HSS0_ATM_MPHY_1_PORT
#undef IX_NPEDL_NPEIMAGE_NPEA_ATM_MPHY_12_PORT
#undef IX_NPEDL_NPEIMAGE_NPEA_DMA
#undef IX_NPEDL_NPEIMAGE_NPEA_HSS_2_PORT
#undef IX_NPEDL_NPEIMAGE_NPEA_ETH
#undef IX_NPEDL_NPEIMAGE_NPEA_ETH_LEARN_FILTER_SPAN_FIREWALL
#undef IX_NPEDL_NPEIMAGE_NPEA_ETH_LEARN_FILTER_SPAN_FIREWALL_VLAN_QOS
#undef IX_NPEDL_NPEIMAGE_NPEA_ETH_SPAN_FIREWALL_VLAN_QOS_HDR_CONV
#undef IX_NPEDL_NPEIMAGE_NPEB_ETH
#undef IX_NPEDL_NPEIMAGE_NPEB_ETH_LEARN_FILTER_SPAN_FIREWALL
/* #undef IX_NPEDL_NPEIMAGE_NPEB_ETH_LEARN_FILTER_SPAN_FIREWALL_VLAN_QOS */
#undef IX_NPEDL_NPEIMAGE_NPEB_ETH_SPAN_FIREWALL_VLAN_QOS_HDR_CONV
#undef IX_NPEDL_NPEIMAGE_NPEB_DMA
#undef IX_NPEDL_NPEIMAGE_NPEC_ETH
#undef IX_NPEDL_NPEIMAGE_NPEC_ETH_LEARN_FILTER_SPAN_FIREWALL
/* #undef IX_NPEDL_NPEIMAGE_NPEC_ETH_LEARN_FILTER_SPAN_FIREWALL_VLAN_QOS */
#undef IX_NPEDL_NPEIMAGE_NPEC_ETH_SPAN_FIREWALL_VLAN_QOS_HDR_CONV
#undef IX_NPEDL_NPEIMAGE_NPEC_DMA

