


#ifndef IXNPEDLNPEMGRECREGISTERS_P_H
#define IXNPEDLNPEMGRECREGISTERS_P_H

#include "IxOsal.h"


#define IX_NPEDL_NPE_BASE (IX_OSAL_IXP400_PERIPHERAL_PHYS_BASE)

#define IX_NPEDL_NPEA_OFFSET (0x6000) /**< NPE-A register base offset */
#define IX_NPEDL_NPEB_OFFSET (0x7000) /**< NPE-B register base offset */
#define IX_NPEDL_NPEC_OFFSET (0x8000) /**< NPE-C register base offset */

#define IX_NPEDL_NPEBASEADDRESS_NPEA (IX_NPEDL_NPE_BASE + IX_NPEDL_NPEA_OFFSET)

#define IX_NPEDL_NPEBASEADDRESS_NPEB (IX_NPEDL_NPE_BASE + IX_NPEDL_NPEB_OFFSET)

#define IX_NPEDL_NPEBASEADDRESS_NPEC (IX_NPEDL_NPE_BASE + IX_NPEDL_NPEC_OFFSET)



#define IX_NPEDL_INS_MEMSIZE_WORDS_NPEA     4096

#define IX_NPEDL_INS_MEMSIZE_WORDS_NPEB     2048

#define IX_NPEDL_INS_MEMSIZE_WORDS_NPEC     2048



#define IX_NPEDL_DATA_MEMSIZE_WORDS_NPEA    2048

#define IX_NPEDL_DATA_MEMSIZE_WORDS_NPEB    2048

#define IX_NPEDL_DATA_MEMSIZE_WORDS_NPEC    2048



#define IX_NPEDL_REG_OFFSET_EXAD             0x00000000		

#define IX_NPEDL_REG_OFFSET_EXDATA           0x00000004

#define IX_NPEDL_REG_OFFSET_EXCTL            0x00000008		

#define IX_NPEDL_REG_OFFSET_EXCT 	     0x0000000C		

#define IX_NPEDL_REG_OFFSET_AP0	             0x00000010		

#define IX_NPEDL_REG_OFFSET_AP1	             0x00000014		

#define IX_NPEDL_REG_OFFSET_AP2	             0x00000018		

#define IX_NPEDL_REG_OFFSET_AP3	             0x0000001C		

#define IX_NPEDL_REG_OFFSET_WFIFO            0x00000020

#define IX_NPEDL_REG_OFFSET_WC	             0x00000024 		

#define IX_NPEDL_REG_OFFSET_PROFCT           0x00000028		

#define IX_NPEDL_REG_OFFSET_STAT	     0x0000002C		

#define IX_NPEDL_REG_OFFSET_CTL	             0x00000030		

#define IX_NPEDL_REG_OFFSET_MBST	     0x00000034		

#define IX_NPEDL_REG_OFFSET_FIFO	     0x00000038		



#define IX_NPEDL_REG_RESET_MBST              0x0000F0F0



#define IX_NPEDL_MASK_WFIFO_VALID            0x80000000

#define IX_NPEDL_MASK_STAT_OFNE              0x00010000

#define IX_NPEDL_MASK_STAT_IFNE              0x00080000




#define IX_NPEDL_EXCTL_CMD_NPE_STEP          0x01

#define IX_NPEDL_EXCTL_CMD_NPE_START         0x02

#define IX_NPEDL_EXCTL_CMD_NPE_STOP          0x03

#define IX_NPEDL_EXCTL_CMD_NPE_CLR_PIPE      0x04

#define IX_NPEDL_EXCTL_CMD_RD_INS_MEM        0x10

#define IX_NPEDL_EXCTL_CMD_WR_INS_MEM        0x11

#define IX_NPEDL_EXCTL_CMD_RD_DATA_MEM       0x12

#define IX_NPEDL_EXCTL_CMD_WR_DATA_MEM       0x13

#define IX_NPEDL_EXCTL_CMD_RD_ECS_REG        0x14

#define IX_NPEDL_EXCTL_CMD_WR_ECS_REG        0x15

#define IX_NPEDL_EXCTL_CMD_CLR_PROFILE_CNT   0x0C



#define IX_NPEDL_EXCTL_STATUS_RUN            0x80000000

#define IX_NPEDL_EXCTL_STATUS_STOP           0x40000000

#define IX_NPEDL_EXCTL_STATUS_CLEAR          0x20000000

#define IX_NPEDL_EXCTL_STATUS_ECS_K          0x00800000



#define IX_NPEDL_ECS_BG_CTXT_REG_0           0x00

#define IX_NPEDL_ECS_BG_CTXT_REG_1           0x01

#define IX_NPEDL_ECS_BG_CTXT_REG_2           0x02

#define IX_NPEDL_ECS_PRI_1_CTXT_REG_0        0x04

#define IX_NPEDL_ECS_PRI_1_CTXT_REG_1        0x05

#define IX_NPEDL_ECS_PRI_1_CTXT_REG_2        0x06

#define IX_NPEDL_ECS_PRI_2_CTXT_REG_0        0x08

#define IX_NPEDL_ECS_PRI_2_CTXT_REG_1        0x09

#define IX_NPEDL_ECS_PRI_2_CTXT_REG_2        0x0A

#define IX_NPEDL_ECS_DBG_CTXT_REG_0          0x0C

#define IX_NPEDL_ECS_DBG_CTXT_REG_1          0x0D

#define IX_NPEDL_ECS_DBG_CTXT_REG_2          0x0E

#define IX_NPEDL_ECS_INSTRUCT_REG            0x11



#define IX_NPEDL_ECS_BG_CTXT_REG_0_RESET     0xA0000000

#define IX_NPEDL_ECS_BG_CTXT_REG_1_RESET     0x01000000

#define IX_NPEDL_ECS_BG_CTXT_REG_2_RESET     0x00008000

#define IX_NPEDL_ECS_PRI_1_CTXT_REG_0_RESET  0x20000080

#define IX_NPEDL_ECS_PRI_1_CTXT_REG_1_RESET  0x01000000

#define IX_NPEDL_ECS_PRI_1_CTXT_REG_2_RESET  0x00008000

#define IX_NPEDL_ECS_PRI_2_CTXT_REG_0_RESET  0x20000080

#define IX_NPEDL_ECS_PRI_2_CTXT_REG_1_RESET  0x01000000

#define IX_NPEDL_ECS_PRI_2_CTXT_REG_2_RESET  0x00008000

#define IX_NPEDL_ECS_DBG_CTXT_REG_0_RESET    0x20000000

#define IX_NPEDL_ECS_DBG_CTXT_REG_1_RESET    0x00000000

#define IX_NPEDL_ECS_DBG_CTXT_REG_2_RESET    0x001E0000

#define IX_NPEDL_ECS_INSTRUCT_REG_RESET      0x1003C00F



#define IX_NPEDL_MASK_ECS_REG_0_ACTIVE       0x80000000

#define IX_NPEDL_MASK_ECS_REG_0_NEXTPC       0x1FFF0000

#define IX_NPEDL_MASK_ECS_REG_0_LDUR         0x00000700

#define IX_NPEDL_MASK_ECS_REG_1_CCTXT        0x000F0000

#define IX_NPEDL_MASK_ECS_REG_1_SELCTXT      0x0000000F

#define IX_NPEDL_MASK_ECS_DBG_REG_2_IF       0x00100000

#define IX_NPEDL_MASK_ECS_DBG_REG_2_IE       0x00080000



#define IX_NPEDL_OFFSET_ECS_REG_0_NEXTPC     16 

#define IX_NPEDL_OFFSET_ECS_REG_0_LDUR        8

#define IX_NPEDL_OFFSET_ECS_REG_1_CCTXT      16

#define IX_NPEDL_OFFSET_ECS_REG_1_SELCTXT     0



#define IX_NPEDL_INSTR_RD_REG_BYTE    0x0FC00000

#define IX_NPEDL_INSTR_RD_REG_SHORT   0x0FC08010

#define IX_NPEDL_INSTR_RD_REG_WORD    0x0FC08210

#define IX_NPEDL_INSTR_WR_REG_BYTE    0x00004000

#define IX_NPEDL_INSTR_WR_REG_SHORT   0x0000C000

#define IX_NPEDL_INSTR_RD_FIFO        0x0F888220    

#define IX_NPEDL_INSTR_RESET_MBOX     0x0FAC8210



#define IX_NPEDL_OFFSET_INSTR_SRC              4

#define IX_NPEDL_OFFSET_INSTR_DEST             9

#define IX_NPEDL_OFFSET_INSTR_COPROC          18



#define IX_NPEDL_MASK_IMMED_INSTR_SRC_DATA         0x1F 

#define IX_NPEDL_MASK_IMMED_INSTR_COPROC_DATA      0xFFE0

#define IX_NPEDL_OFFSET_IMMED_INSTR_COPROC_DATA    5

#define IX_NPEDL_DISPLACE_IMMED_INSTR_COPROC_DATA \
     (IX_NPEDL_OFFSET_INSTR_COPROC - IX_NPEDL_OFFSET_IMMED_INSTR_COPROC_DATA)

#define IX_NPEDL_WR_INSTR_LDUR                     1

#define IX_NPEDL_RD_INSTR_LDUR                     0


typedef enum
{
    IX_NPEDL_CTXT_REG_STEVT = 0,  /**< identifies STEVT   */
    IX_NPEDL_CTXT_REG_STARTPC,    /**< identifies STARTPC */
    IX_NPEDL_CTXT_REG_REGMAP,     /**< identifies REGMAP  */
    IX_NPEDL_CTXT_REG_CINDEX,     /**< identifies CINDEX  */
    IX_NPEDL_CTXT_REG_MAX         /**< Total number of Context Store registers */
} IxNpeDlCtxtRegNum;



#define IX_NPEDL_CTXT_REG_ADDR_STEVT      0x0000001B

#define IX_NPEDL_CTXT_REG_ADDR_STARTPC    0x0000001C

#define IX_NPEDL_CTXT_REG_ADDR_REGMAP     0x0000001E

#define IX_NPEDL_CTXT_REG_ADDR_CINDEX     0x0000001F



#define IX_NPEDL_CTXT_REG_RESET_STEVT     0x80

#define IX_NPEDL_CTXT_REG_RESET_STARTPC   0x0000

#define IX_NPEDL_CTXT_REG_RESET_REGMAP    0x0820

#define IX_NPEDL_CTXT_REG_RESET_CINDEX    0x00



#define IX_NPEDL_CTXT_NUM_MIN             0

#define IX_NPEDL_CTXT_NUM_MAX             15



#define IX_NPEDL_TOTAL_NUM_PHYS_REG               32

#define IX_NPEDL_OFFSET_PHYS_REG_ADDR_REGMAP      1

#define IX_NPEDL_MASK_PHYS_REG_ADDR_LOGICAL_ADDR   0x1

#endif /* IXNPEDLNPEMGRECREGISTERS_P_H */
