


#ifndef IXVERSIONID_H
#define IXVERSIONID_H

#define IX_VERSION_ID "2_0"

#define IX_VERSION_ADSL_ID "1_12"


#define IX_VERSION_USBRNDIS_ID "1_9"

#define IX_VERSION_I2C_LINUX_ID "1_0"

#define LINUX_ETHERNET_DRIVER_PATCH_ID "1_4"

#define LINUX_INTEGRATION_PATCH_ID "1_3"

#define LINUX_ETHERNET_README_ID "1_3"


#define LINUX_INTEGRATION_README_ID "1_3"

#define LINUX_I2C_DRIVER_README_ID "1_0"


#define IXP425_ETH_UPDATE_NF_BRIDGE_ID "1_3"

#define IX_VERSION_INTERNAL_ID "SQA3_5"

#define IX_VERSION_COMPATIBLE_TORNADO "Tornado2_2_1-PNE2_0"

#define IX_VERSION_COMPATIBLE_LINUX "MVL3_1"


#endif /* IXVERSIONID_H */

