
#ifndef __CUST_GPIO_USAGE_H__
#define __CUST_GPIO_USAGE_H__


#define GPIO_AST_CS_PIN         GPIO13
#define GPIO_AST_CS_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_AST_CS_PIN_M_EINT  GPIO_MODE_02
#define GPIO_AST_CS_PIN_M_PWM  GPIO_MODE_03
#define GPIO_AST_CS_PIN_M_LPCE1B   GPIO_MODE_01
#define GPIO_AST_CS_PIN_LPCE     1

#define GPIO_CMMB_RST_PIN         GPIO47
#define GPIO_CMMB_RST_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_CMMB_RST_PIN_M_IRQ  GPIO_MODE_06

#define GPIO_SPEAKER_EN_PIN         GPIO48
#define GPIO_SPEAKER_EN_PIN_M_GPIO  GPIO_MODE_00

#define GPIO_CMMB_LDO_EN_PIN         GPIO50
#define GPIO_CMMB_LDO_EN_PIN_M_GPIO  GPIO_MODE_00

#define GPIO_CTP_RST_PIN         GPIO54
#define GPIO_CTP_RST_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_CTP_RST_PIN_M_CLK  GPIO_MODE_03
#define GPIO_CTP_RST_PIN_CLK     CLK_OUT5
#define GPIO_CTP_RST_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_I2S0_CK_PIN         GPIO56
#define GPIO_I2S0_CK_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_I2S0_CK_PIN_M_I2S1_CK   GPIO_MODE_01
#define GPIO_I2S0_CK_PIN_M_I2S0_CK   GPIO_MODE_04

#define GPIO_COMBO_I2S_CK_PIN         GPIO56
#define GPIO_COMBO_I2S_CK_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_COMBO_I2S_CK_PIN_M_I2S1_CK   GPIO_MODE_01
#define GPIO_COMBO_I2S_CK_PIN_M_I2S0_CK   GPIO_MODE_04

#define GPIO_I2S0_WS_PIN         GPIO57
#define GPIO_I2S0_WS_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_I2S0_WS_PIN_M_EINT  GPIO_MODE_02
#define GPIO_I2S0_WS_PIN_M_I2S1_WS   GPIO_MODE_01
#define GPIO_I2S0_WS_PIN_M_I2S0_WS   GPIO_MODE_04

#define GPIO_COMBO_I2S_WS_PIN         GPIO57
#define GPIO_COMBO_I2S_WS_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_COMBO_I2S_WS_PIN_M_EINT  GPIO_MODE_02
#define GPIO_COMBO_I2S_WS_PIN_M_I2S1_WS   GPIO_MODE_01
#define GPIO_COMBO_I2S_WS_PIN_M_I2S0_WS   GPIO_MODE_04

#define GPIO_I2S0_DAT_PIN         GPIO58
#define GPIO_I2S0_DAT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_I2S0_DAT_PIN_M_EINT  GPIO_MODE_02
#define GPIO_I2S0_DAT_PIN_M_I2S1_DAT   GPIO_MODE_01
#define GPIO_I2S0_DAT_PIN_M_I2S0_DAT   GPIO_MODE_04

#define GPIO_COMBO_I2S_DAT_PIN         GPIO58
#define GPIO_COMBO_I2S_DAT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_COMBO_I2S_DAT_PIN_M_EINT  GPIO_MODE_02
#define GPIO_COMBO_I2S_DAT_PIN_M_I2S1_DAT   GPIO_MODE_01
#define GPIO_COMBO_I2S_DAT_PIN_M_I2S0_DAT   GPIO_MODE_04

#define GPIO_COMBO_RST_PIN         GPIO59
#define GPIO_COMBO_RST_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_COMBO_RST_PIN_M_EINT  GPIO_MODE_02
#define GPIO_COMBO_RST_PIN_M_PWM  GPIO_MODE_03
#define GPIO_COMBO_RST_PIN_M_DAIRSTB   GPIO_MODE_01

#define GPIO_ACCDET_EINT_PIN         GPIO60
#define GPIO_ACCDET_EINT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_ACCDET_EINT_PIN_M_EINT  GPIO_MODE_01
#define GPIO_ACCDET_EINT_PIN_M_PWM  GPIO_MODE_03

#define GPIO_PMIC_EINT_PIN         GPIO61
#define GPIO_PMIC_EINT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_PMIC_EINT_PIN_M_EINT  GPIO_MODE_01
#define GPIO_PMIC_EINT_PIN_M_PWM  GPIO_MODE_03

#define GPIO_PCM_DAIPCMOUT_PIN         GPIO62
#define GPIO_PCM_DAIPCMOUT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_PCM_DAIPCMOUT_PIN_M_EINT  GPIO_MODE_02
#define GPIO_PCM_DAIPCMOUT_PIN_M_PWM  GPIO_MODE_03
#define GPIO_PCM_DAIPCMOUT_PIN_M_DAIPCMOUT   GPIO_MODE_01

#define GPIO_PCM_DAICLK_PIN         GPIO63
#define GPIO_PCM_DAICLK_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_PCM_DAICLK_PIN_M_CLK  GPIO_MODE_01
#define GPIO_PCM_DAICLK_PIN_M_EINT  GPIO_MODE_02
#define GPIO_PCM_DAICLK_PIN_M_PWM  GPIO_MODE_03

#define GPIO_PCM_DAIPCMIN_PIN         GPIO64
#define GPIO_PCM_DAIPCMIN_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_PCM_DAIPCMIN_PIN_M_EINT  GPIO_MODE_02
#define GPIO_PCM_DAIPCMIN_PIN_M_PWM  GPIO_MODE_03
#define GPIO_PCM_DAIPCMIN_PIN_M_DAIPCMIN   GPIO_MODE_01

#define GPIO_PCM_DAISYNC_PIN         GPIO65
#define GPIO_PCM_DAISYNC_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_PCM_DAISYNC_PIN_M_EINT  GPIO_MODE_02
#define GPIO_PCM_DAISYNC_PIN_M_PWM  GPIO_MODE_03
#define GPIO_PCM_DAISYNC_PIN_M_BTSYNC   GPIO_MODE_01

#define GPIO_PWM_1_PIN         GPIO67
#define GPIO_PWM_1_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_PWM_1_PIN_M_EINT  GPIO_MODE_02
#define GPIO_PWM_1_PIN_M_PWM  GPIO_MODE_01

#define GPIO_WIFI_EINT_PIN         GPIO69
#define GPIO_WIFI_EINT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_WIFI_EINT_PIN_M_CLK  GPIO_MODE_04
#define GPIO_WIFI_EINT_PIN_M_EINT  GPIO_MODE_01
#define GPIO_WIFI_EINT_PIN_M_PWM  GPIO_MODE_02
#define GPIO_WIFI_EINT_PIN_CLK     CLK_OUT2
#define GPIO_WIFI_EINT_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_UART_UTXD3_PIN         GPIO71
#define GPIO_UART_UTXD3_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_UART_UTXD3_PIN_M_EINT  GPIO_MODE_02
#define GPIO_UART_UTXD3_PIN_M_PWM  GPIO_MODE_04
#define GPIO_UART_UTXD3_PIN_M_UTXD   GPIO_MODE_01

#define GPIO_GPS_SYNC_PIN         GPIO72
#define GPIO_GPS_SYNC_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_GPS_SYNC_PIN_M_CLK  GPIO_MODE_04
#define GPIO_GPS_SYNC_PIN_M_EINT  GPIO_MODE_01
#define GPIO_GPS_SYNC_PIN_M_PWM  GPIO_MODE_02
#define GPIO_GPS_SYNC_PIN_M_GPS_SYNC   GPIO_MODE_05
#define GPIO_GPS_SYNC_PIN_CLK     CLK_OUT1
#define GPIO_GPS_SYNC_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_AST_INTR_PIN         GPIO73
#define GPIO_AST_INTR_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_AST_INTR_PIN_M_CLK  GPIO_MODE_02
#define GPIO_AST_INTR_PIN_M_EINT  GPIO_MODE_01
#define GPIO_AST_INTR_PIN_M_USB_DRVVBUS   GPIO_MODE_05
#define GPIO_AST_INTR_PIN_CLK     CLK_OUT0
#define GPIO_AST_INTR_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_CTP_EINT_PIN         GPIO75
#define GPIO_CTP_EINT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_CTP_EINT_PIN_M_EINT  GPIO_MODE_01
#define GPIO_CTP_EINT_PIN_M_PWM  GPIO_MODE_02

#define GPIO_AST_WAKEUP_INTR_PIN         GPIO76
#define GPIO_AST_WAKEUP_INTR_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_AST_WAKEUP_INTR_PIN_M_CLK  GPIO_MODE_04
#define GPIO_AST_WAKEUP_INTR_PIN_M_EINT  GPIO_MODE_01
#define GPIO_AST_WAKEUP_INTR_PIN_M_PWM  GPIO_MODE_02
#define GPIO_AST_WAKEUP_INTR_PIN_CLK     CLK_OUT4
#define GPIO_AST_WAKEUP_INTR_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_GSE_1_EINT_PIN         GPIO77
#define GPIO_GSE_1_EINT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_GSE_1_EINT_PIN_M_EINT  GPIO_MODE_02
#define GPIO_GSE_1_EINT_PIN_M_PWM  GPIO_MODE_04

#define GPIO_COMBO_BGF_EINT_PIN         GPIO78
#define GPIO_COMBO_BGF_EINT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_COMBO_BGF_EINT_PIN_M_EINT  GPIO_MODE_01
#define GPIO_COMBO_BGF_EINT_PIN_M_PWM  GPIO_MODE_02

#define GPIO_UART_URXD3_PIN         GPIO79
#define GPIO_UART_URXD3_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_UART_URXD3_PIN_M_EINT  GPIO_MODE_02
#define GPIO_UART_URXD3_PIN_M_PWM  GPIO_MODE_04
#define GPIO_UART_URXD3_PIN_M_URXD   GPIO_MODE_01

#define GPIO_ALS_EINT_PIN         GPIO81
#define GPIO_ALS_EINT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_ALS_EINT_PIN_M_CLK  GPIO_MODE_04
#define GPIO_ALS_EINT_PIN_M_EINT  GPIO_MODE_01
#define GPIO_ALS_EINT_PIN_M_PWM  GPIO_MODE_02
#define GPIO_ALS_EINT_PIN_CLK     CLK_OUT3
#define GPIO_ALS_EINT_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_SPI_CS_PIN         GPIO83
#define GPIO_SPI_CS_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_SPI_CS_PIN_M_EINT  GPIO_MODE_02
#define GPIO_SPI_CS_PIN_M_SPI_CSN   GPIO_MODE_01
#define GPIO_SPI_CS_PIN_M_SPI_CSN   GPIO_MODE_04

#define GPIO_SPI_MISO_PIN         GPIO84
#define GPIO_SPI_MISO_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_SPI_MISO_PIN_M_EINT  GPIO_MODE_02
#define GPIO_SPI_MISO_PIN_M_SPI_MI   GPIO_MODE_01

#define GPIO_SPI_MOSI_PIN         GPIO85
#define GPIO_SPI_MOSI_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_SPI_MOSI_PIN_M_CLK  GPIO_MODE_03
#define GPIO_SPI_MOSI_PIN_M_EINT  GPIO_MODE_02
#define GPIO_SPI_MOSI_PIN_M_SPI_MO   GPIO_MODE_01
#define GPIO_SPI_MOSI_PIN_M_SPI_MI   GPIO_MODE_04
#define GPIO_SPI_MOSI_PIN_CLK     CLK_OUT5
#define GPIO_SPI_MOSI_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_SPI_SCK_PIN         GPIO86
#define GPIO_SPI_SCK_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_SPI_SCK_PIN_M_CLK  GPIO_MODE_01
#define GPIO_SPI_SCK_PIN_M_EINT  GPIO_MODE_02

#define GPIO_I2C0_SCA_PIN         GPIO87
#define GPIO_I2C0_SCA_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_I2C0_SCA_PIN_M_CLK  GPIO_MODE_03
#define GPIO_I2C0_SCA_PIN_M_EINT  GPIO_MODE_02
#define GPIO_I2C0_SCA_PIN_M_SCL   GPIO_MODE_01
#define GPIO_I2C0_SCA_PIN_CLK     CLK_OUT4
#define GPIO_I2C0_SCA_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_I2C0_SDA_PIN         GPIO88
#define GPIO_I2C0_SDA_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_I2C0_SDA_PIN_M_CLK  GPIO_MODE_03
#define GPIO_I2C0_SDA_PIN_M_EINT  GPIO_MODE_02
#define GPIO_I2C0_SDA_PIN_M_SDA   GPIO_MODE_01
#define GPIO_I2C0_SDA_PIN_CLK     CLK_OUT3
#define GPIO_I2C0_SDA_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_AST_WAKEUP_PIN         GPIO89
#define GPIO_AST_WAKEUP_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_AST_WAKEUP_PIN_M_CLK  GPIO_MODE_04
#define GPIO_AST_WAKEUP_PIN_M_EINT  GPIO_MODE_02
#define GPIO_AST_WAKEUP_PIN_CLK     CLK_OUT1
#define GPIO_AST_WAKEUP_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_AST_AFC_SWITCH_PIN         GPIO91
#define GPIO_AST_AFC_SWITCH_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_AST_AFC_SWITCH_PIN_M_CLK  GPIO_MODE_04
#define GPIO_AST_AFC_SWITCH_PIN_M_EINT  GPIO_MODE_02
#define GPIO_AST_AFC_SWITCH_PIN_CLK     CLK_OUT4
#define GPIO_AST_AFC_SWITCH_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_AST_RST_PIN         GPIO92
#define GPIO_AST_RST_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_AST_RST_PIN_M_CLK  GPIO_MODE_01
#define GPIO_AST_RST_PIN_M_EINT  GPIO_MODE_02
#define GPIO_AST_RST_PIN_CLK     CLK_OUT5
#define GPIO_AST_RST_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_AST_CLK32K_PIN         GPIO94
#define GPIO_AST_CLK32K_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_AST_CLK32K_PIN_M_CLK  GPIO_MODE_04
#define GPIO_AST_CLK32K_PIN_M_EINT  GPIO_MODE_02
#define GPIO_AST_CLK32K_PIN_CLK     CLK_OUT3
#define GPIO_AST_CLK32K_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_KPD_KCOL7_PIN         GPIO96
#define GPIO_KPD_KCOL7_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_KPD_KCOL7_PIN_M_CLK  GPIO_MODE_03
#define GPIO_KPD_KCOL7_PIN_M_EINT  GPIO_MODE_02
#define GPIO_KPD_KCOL7_PIN_M_KP_COL   GPIO_MODE_01
#define GPIO_KPD_KCOL7_PIN_CLK     CLK_OUT5
#define GPIO_KPD_KCOL7_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_KPD_KROW1_PIN         GPIO97
#define GPIO_KPD_KROW1_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_KPD_KROW1_PIN_M_CLK  GPIO_MODE_03
#define GPIO_KPD_KROW1_PIN_M_EINT  GPIO_MODE_02
#define GPIO_KPD_KROW1_PIN_M_KP_ROW   GPIO_MODE_01
#define GPIO_KPD_KROW1_PIN_CLK     CLK_OUT3
#define GPIO_KPD_KROW1_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_KPD_KROW0_PIN         GPIO98
#define GPIO_KPD_KROW0_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_KPD_KROW0_PIN_M_CLK  GPIO_MODE_03
#define GPIO_KPD_KROW0_PIN_M_EINT  GPIO_MODE_02
#define GPIO_KPD_KROW0_PIN_M_KP_ROW   GPIO_MODE_01
#define GPIO_KPD_KROW0_PIN_CLK     CLK_OUT4
#define GPIO_KPD_KROW0_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_KPD_KCOL0_PIN         GPIO103
#define GPIO_KPD_KCOL0_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_KPD_KCOL0_PIN_M_EINT  GPIO_MODE_02
#define GPIO_KPD_KCOL0_PIN_M_PWM  GPIO_MODE_03
#define GPIO_KPD_KCOL0_PIN_M_KP_COL   GPIO_MODE_01

#define GPIO_CMMB_EINT_PIN         GPIO107
#define GPIO_CMMB_EINT_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_CMMB_EINT_PIN_M_EINT  GPIO_MODE_02
#define GPIO_CMMB_EINT_PIN_M_KP_ROW   GPIO_MODE_01

#define GPIO_KPD_KCOL1_PIN         GPIO108
#define GPIO_KPD_KCOL1_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_KPD_KCOL1_PIN_M_EINT  GPIO_MODE_02
#define GPIO_KPD_KCOL1_PIN_M_PWM  GPIO_MODE_03
#define GPIO_KPD_KCOL1_PIN_M_KP_COL   GPIO_MODE_01

#define GPIO_KPD_KCOL6_PIN         GPIO109
#define GPIO_KPD_KCOL6_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_KPD_KCOL6_PIN_M_EINT  GPIO_MODE_02
#define GPIO_KPD_KCOL6_PIN_M_PWM  GPIO_MODE_03
#define GPIO_KPD_KCOL6_PIN_M_KP_COL   GPIO_MODE_01

#define GPIO_COMBO_6620_LDO_EN_PIN         GPIO124
#define GPIO_COMBO_6620_LDO_EN_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_COMBO_6620_LDO_EN_PIN_M_EINT  GPIO_MODE_02

#define GPIO_COMBO_PMU_EN_PIN         GPIO126
#define GPIO_COMBO_PMU_EN_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_COMBO_PMU_EN_PIN_M_EINT  GPIO_MODE_02

#define GPIO_GPS_LNA_PIN         GPIO127
#define GPIO_GPS_LNA_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_GPS_LNA_PIN_M_EINT  GPIO_MODE_02

#define GPIO_UART_UTXD1_PIN         GPIO157
#define GPIO_UART_UTXD1_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_UART_UTXD1_PIN_M_EINT  GPIO_MODE_02
#define GPIO_UART_UTXD1_PIN_M_UTXD   GPIO_MODE_01

#define GPIO_UART_UTXD4_PIN         GPIO158
#define GPIO_UART_UTXD4_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_UART_UTXD4_PIN_M_EINT  GPIO_MODE_02
#define GPIO_UART_UTXD4_PIN_M_UTXD   GPIO_MODE_01

#define GPIO_UART_URXD4_PIN         GPIO159
#define GPIO_UART_URXD4_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_UART_URXD4_PIN_M_EINT  GPIO_MODE_02
#define GPIO_UART_URXD4_PIN_M_URXD   GPIO_MODE_01

#define GPIO_UART_URXD1_PIN         GPIO160
#define GPIO_UART_URXD1_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_UART_URXD1_PIN_M_URXD   GPIO_MODE_01

#define GPIO_CAMERA_CMPDN1_PIN         GPIO220
#define GPIO_CAMERA_CMPDN1_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_CAMERA_CMPDN1_PIN_M_EINT  GPIO_MODE_02
#define GPIO_CAMERA_CMPDN1_PIN_M_PWM  GPIO_MODE_01

#define GPIO_I2C1_SCA_PIN         GPIO222
#define GPIO_I2C1_SCA_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_I2C1_SCA_PIN_M_EINT  GPIO_MODE_02
#define GPIO_I2C1_SCA_PIN_M_SCL   GPIO_MODE_01

#define GPIO_I2C1_SDA_PIN         GPIO224
#define GPIO_I2C1_SDA_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_I2C1_SDA_PIN_M_EINT  GPIO_MODE_02
#define GPIO_I2C1_SDA_PIN_M_SDA   GPIO_MODE_01

#define GPIO_CAMERA_CMPDN_PIN         GPIO228
#define GPIO_CAMERA_CMPDN_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_CAMERA_CMPDN_PIN_M_EINT  GPIO_MODE_02
#define GPIO_CAMERA_CMPDN_PIN_M_CMPDN   GPIO_MODE_01

#define GPIO_CAMERA_CMRST1_PIN         GPIO230
#define GPIO_CAMERA_CMRST1_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_CAMERA_CMRST1_PIN_M_CLK  GPIO_MODE_03
#define GPIO_CAMERA_CMRST1_PIN_M_EINT  GPIO_MODE_02


/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */



#endif /* __CUST_GPIO_USAGE_H__ */



