CROSS_COMPILE ?= nios2-elf-

STANDALONE_LOAD_ADDR = 0x02000000 -L $(gcclibdir)

PLATFORM_CPPFLAGS += -DCONFIG_NIOS2 -D__NIOS2__
PLATFORM_CPPFLAGS += -ffixed-r15 -G0

LDSCRIPT ?= $(SRCTREE)/$(CPUDIR)/u-boot.lds
