CROSS_COMPILE ?= sh4-linux-

STANDALONE_LOAD_ADDR = 0x8C000000
ifeq ($(CPU),sh2)
STANDALONE_LOAD_ADDR += -EB
endif

PLATFORM_CPPFLAGS += -DCONFIG_SH -D__SH__
PLATFORM_LDFLAGS += -e $(TEXT_BASE) --defsym reloc_dst=$(TEXT_BASE)

LDSCRIPT := $(SRCTREE)/$(CPUDIR)/u-boot.lds
